[workspace]
authors = ["pedestrianlove <jsli@linux.com>"]
channels = ["conda-forge"]
name = "CHIP8"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
sox = ">=14.4.2,<15"

[pypi-dependencies]
pygame = ">=2.6.1, <3"
